language: node_js
sudo: false 
dist: xenial
notifications:
  email:
    recipients:
    - kschwarz@hexonet.net
    on_success: never
    on_failure: always
cache:
  directories:
    - ~/.npm
    - node_modules
node_js:
  - '11'
  - '10'
  - '9'
  - '8'
before_install:
- npm prune
install:
- npm i
before_script:
- npm run build
- npm run lint
script:
# replace the below with unit tests one day
- node ./dist/app_session.js
- node ./dist/app_nosession.js