language: node_js
dist: bionic
notifications:
  email:
    recipients:
      - kschwarz@hexonet.net
    on_success: never
    on_failure: always
node_js:
  - "12"
  - "10"
before_install:
  - npm prune
install:
  - travis_retry npm i
before_script:
  - npm run build
  - npm run lint
script:
  - npm run test
