language: node_js
dist: xenial
notifications:
  email:
    recipients:
    - kschwarz@hexonet.net
    on_success: never
    on_failure: always
cache:
  directories:
    - ~/.npm
    - node_modules
node_js:
  - '11'
  - '10'
  - '9'
  - '8'
# Trigger a push build on master and dependabot branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^dependabot.*$/
before_install:
  - npm prune
install:
  - travis_retry npm i
before_script:
  - npm run build
  - npm run lint
script:
# replace the below with unit tests one day
  - node ./dist/app_session.js
  - node ./dist/app_nosession.js