name: Dependabot auto-merge
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    uses: ./.github/workflows/test.yml
    secrets: inherit
    permissions:
      contents: read

  dependabot:
    if: ${{ github.actor == 'dependabot[bot]' }}
    name: Auto-merge Dependabot PR
    runs-on: ${{ vars.RTLDEV_MW_CI_OS }}
    needs: tests
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable auto-merge for Dependabot PRs
        # No exceptions, NODE-SDK is the only dependency we have
        run: gh pr merge --auto -d -r "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.RTLDEV_MW_CI_TOKEN}}
