name: Release
on: [push, pull_request]

jobs:
  test:
    name: Test @ NodeJS LTS - x86 - ubuntu-latest
    # Support [skip ci] out of box with github actions Workaround
    # Only works for push https://github.com/actions/runner/issues/774
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && contains(toJson(github.event.commits), '[skip ci]') == false)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS LTS
        uses: actions/setup-node@v2
      - name: Build & Validation
        run: |
          npm prune && npm i
          npm run build
          npm run lint
          npm run test
