name: Release

on:
  push:
    branches:
      - "**"

  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    name: Test @ NodeJS LTS - x86 - ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup NodeJS LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}              
          DEFAULT_BRANCH: master
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_TYPESCRIPT_ES: true         
          FILTER_REGEX_INCLUDE: "/src/*"       
      - name: Build & Validation
        run: |
          npm ci
          npm run test
