name: Lint & Test

on:
  workflow_call:

jobs:
  test:
    name: 🧪 Testing
    runs-on: ${{ vars.RTLDEV_MW_CI_OS }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup NodeJS LTS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.RTLDEV_MW_CI_NODE_VERSION }}
          check-latest: true
      - name: Lint Code Base
        uses: github/super-linter/slim@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: master
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_TYPESCRIPT_ES: true
          FILTER_REGEX_INCLUDE: "/src/*"
      - name: Build & Validation
        run: |
          npm ci
          npm run test
